function DependancyGraph(filepath,fullGSpath,filepath_dot,copy_allowed)
% Depedancy Graph - Developp a Depedancy Graph of your file
% V3 - Stéphane Nachar (stephane.nachar@ens-cachan.fr)
% 
% ! 1) Graphwiz required (www.graphviz.org/)
% ! 2) Run once your code before 
% !    Or Add all paths required for your code before running DependancyGraph
% ! 3) Some files are not detected by MATLAB(c)'s requiredFilesAndProducts :
% !  To provide meaningful results, the Dependency Report requires the following:
% !      - The search path when you run the report is the same as when you run the files in the folder. (That is, the current folder is at the top of the search path.)
% !      - The files in the folder for which you are running the report do not change the search path or otherwise manipulate it.
% !      - The files in the folder do not load variables, or otherwise create name clashes that result in different program elements with the same name.
%
% Input :
% > filepath : FULL path of your file (Exemple : 'C:\test.m')
% > filepath_dot (Optional) : Fullpath of the Graphwiz program dot.exe
%                             If not specified, using default path for windows x64
%                             '"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe"'
% > fullGSpath   (Optional) : FULL GS path, including the file name, to
%                   the GS executable (on win32 it could be c:\program
%                   files\gs\gs8.14\bin\gswin32c.exe). The existence for
%                   fullGsPath will be checked for if given. On the other
%                   hand, if fullGsPath is not given or empty it defaults
%                   to 'gswin32c' for pcs and 'gs' for unix and the
%                   existence will not be checked for. But in this, latter
%                   case, GS's path must be in the system's path variable.
% > copy_allowed (Optionnal) : Allow copy the required files to a folder
%                               with CopyMUseful.m
% Output :
% > graphwiz.dot : Input file for Graphwiz
% > Depedency.png : Image PNG generated by Graphwiz
% > Depedency.eps : Image PS  generated by Graphwiz
% > Depedency.pdf : PDF       generated by GS with eps2pdf
%
% (eps2pdf is developped by Primoz Cermelj, 24.08.2004
%   (c) Primoz Cermelj, primoz.cermelj@email.si )

addpath('Files_Depedancy');
%% Analyse du nom de ficher
[fpath,fname,~] = fileparts(filepath);
if strcmp(fpath,'')
   error('Filepath is not the full path. Please use full path.'); 
end
genpath(fpath);
%filepath='C:\Users\Phanou\Desktop\Stage\Programme\GRENAT\code_lancement\lancement_stephane.m';
%fullGSpath = 'D:\PortableApps\Ghostscript\bin\gswin64c.exe';

%% Analyse et création des structures Nodes & Connexions 
[Nodes,Connexions]=FileAnalysis(filepath);

%% Création du fichier pour Graphwiz 
[filepath_output]=GraphwizConversion(Nodes,Connexions);

%% Génération des images via Graphwiz 
if nargin<3
   warning('Filepath for dot (Graphwiz) is not specified : using default path for windows x64');
   filepath_dot='"C:\Program Files (x86)\Graphviz2.38\bin\dot.exe"';
end

system([filepath_dot,' -Tpng ',filepath_output,' -o ',fname,'.png']);
system([filepath_dot,' -Teps ',filepath_output,' -o ',fname,'.eps']);

if nargin==1
    warning('Filepath for GS is not specified : using default path');
    eps2pdf([fname,'.eps']);
else
    eps2pdf([fname,'.eps'],fullGSpath);
end

if nargin==4
    print('CopyAllowed')
    CopyMUseful(Nodes);
end
end